name: Documents Build

on: [push, workflow_dispatch]

jobs:

##
## For langs that require the special fonts ( Russian, Chinese, etc.)
## The `stable-full` version of pandocker is required, you can activate
## it with the `TAG` environment variable, like this
##
## TAG=stable-full ./tools/docker/pandoc_makedocs.sh ....
##

  en:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Generate English PDF
      run: ./tools/docker/pandoc_makedocs.sh Document SNAPSHOT

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-SNAPSHOT-en
        path: OWASP_MASVS-SNAPSHOT-en*

  de:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Generate German PDF
      run: ./tools/docker/pandoc_makedocs.sh Document-de SNAPSHOT

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-SNAPSHOT-de
        path: OWASP_MASVS-SNAPSHOT-de*

  fa:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Generate Persian PDF
      run: TAG=stable-full ./tools/docker/pandoc_makedocs.sh Document-fa SNAPSHOT
      env:
        LATEX_TEMPLATE: default # there's a bug in the eisvogel template

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-SNAPSHOT-fa
        path: OWASP_MASVS-SNAPSHOT-fa*

  es:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Generate Spanish PDF
      run: ./tools/docker/pandoc_makedocs.sh Document-es SNAPSHOT

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-SNAPSHOT-es
        path: OWASP_MASVS-SNAPSHOT-es*

  fr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Generate French PDF
      run: ./tools/docker/pandoc_makedocs.sh Document-fr SNAPSHOT

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-SNAPSHOT-fr 
        path: OWASP_MASVS-SNAPSHOT-fr*

  hi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Generate Hindi PDF
      run: TAG=stable-full ./tools/docker/pandoc_makedocs.sh Document-hi SNAPSHOT

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-SNAPSHOT-hi
        path: OWASP_MASVS-SNAPSHOT-hi*

  ja:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Generate Japanese PDF
      run: TAG=stable-full ./tools/docker/pandoc_makedocs.sh Document-ja SNAPSHOT

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-SNAPSHOT-ja
        path: OWASP_MASVS-SNAPSHOT-ja*

  ko:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Generate Korean PDF
      run: TAG=stable-full ./tools/docker/pandoc_makedocs.sh Document-ko SNAPSHOT

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-SNAPSHOT-ko
        path: OWASP_MASVS-SNAPSHOT-ko*

  pt-br:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Generate Brazilian Portuguese PDF
      run: ./tools/docker/pandoc_makedocs.sh Document-ptbr SNAPSHOT

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-SNAPSHOT-ptbr
        path: OWASP_MASVS-SNAPSHOT-ptbr*


  pt-pt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Generate Portugal Portuguese PDF
      run: ./tools/docker/pandoc_makedocs.sh Document-ptpt SNAPSHOT

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-SNAPSHOT-ptpt
        path: OWASP_MASVS-SNAPSHOT-ptpt*


  ru:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Generate Russian PDF
      run: TAG=stable-full ./tools/docker/pandoc_makedocs.sh Document-ru SNAPSHOT

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-SNAPSHOT-ru
        path: OWASP_MASVS-SNAPSHOT-ru*

  zhcn:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Generate Simplified Chinese PDF
      run: TAG=stable-full ./tools/docker/pandoc_makedocs.sh Document-zhcn SNAPSHOT

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-SNAPSHOT-zhcn
        path: OWASP_MASVS-SNAPSHOT-zhcn*

  zhtw:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Generate Traditional Chinese PDF
      run: TAG=stable-full ./tools/docker/pandoc_makedocs.sh Document-zhtw SNAPSHOT

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-SNAPSHOT-zhtw
        path: OWASP_MASVS-SNAPSHOT-zhtw*


  export:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Pull the Docker image
      run: docker pull owasp/masvs-docgenerator:0.2
    # only use below when testing new container builds
    # - name: Build the Docker image
    #   run: docker build ./tools/docker --tag masvs-generator:latest

    - name: Generate python scripts (csv)
      run: docker run -v ${PWD}:/documents owasp/masvs-docgenerator:0.2 'cd /documents/tools && python3 export.py --format csv --lang en > OWASP_MASVS-SNAPSHOT.csv'
    - name: Generate python scripts (json)
      run: docker run -v ${PWD}:/documents owasp/masvs-docgenerator:0.2 'cd /documents/tools && python3 export.py --format json --lang en > OWASP_MASVS-SNAPSHOT.json'
    - name: Generate python scripts (xml)
      run: docker run -v ${PWD}:/documents owasp/masvs-docgenerator:0.2 'cd /documents/tools && python3 export.py --format xml --lang en > OWASP_MASVS-SNAPSHOT.xml'
    - name: Upload CSV export
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_MASVS-SNAPSHOT.csv
        path: tools/OWASP_MASVS-SNAPSHOT.csv
    - name: Upload JSON export
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-SNAPSHOT.json
        path: tools/OWASP_MASVS-SNAPSHOT.json
    - name: Upload XML export
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-SNAPSHOT.xml
        path: tools/OWASP_MASVS-SNAPSHOT.xml

